### ISSUE TITLE
Import 3d player model

### ISSUE THREAD

**Issue by GambuzX** [NIAEFEUP/genetic-fighting-game#3]

**Comment by DoStini** [comment]
Do you have the link for the model?

**Comment by GambuzX** [comment]
Nope, we still need to find one

**Comment by DoStini** [comment]
What was the website you showed us in the meeting?

**Comment by GambuzX** [comment]
Mixamo, but that is for animations

**Comment by GambuzX** [comment]
Maybe something around this:
https://www.turbosquid.com/Search/3D-Models/free/humanoid
http://blog.inf.ed.ac.uk/atate/2015/09/21/unity3d-characters/

**Comment by GambuzX** [comment]
Just find one you like
