### ISSUE TITLE
Create Game design document

### ISSUE THREAD

**Issue by GambuzX** [NIAEFEUP/genetic-fighting-game#6]
Create a document to specify our vision of the game, so that everyone can understand it
Something simple

**Comment by DinisSousa2003** [comment]
Created the game deign document using a template, still has blank spaces as the mechanics and other aspects of the project still have to be worked out.
https://join.nuclino.com/lolxd?link=BEtWmjm0XplnvYFu-xeGfa

**Comment by GambuzX** [comment]
Is this free to use for everyone? If not, it may be a good idea to move this to Google Docs so that we can easily update the document in the future

**Comment by GambuzX** [comment]
Either way, please create a Pull Request and add the link to the document in the README

**Comment by DinisSousa2003** [comment]
Yes it is, the link works as an invite so everyone can manipulate or read.
